var searchData=
[
  ['v',['V',['../union_a_p_s_r___type.html#a8004d224aacb78ca37774c35f9156e7e',1,'APSR_Type::V()'],['../unionx_p_s_r___type.html#af14df16ea0690070c45b95f2116b7a0a',1,'xPSR_Type::V()']]],
  ['val',['VAL',['../struct_sys_tick___type.html#a0997ff20f11817f8246e8f0edac6f4e4',1,'SysTick_Type']]],
  ['vcoroutineschedule',['vCoRoutineSchedule',['../group__v_co_routine_schedule.html',1,'']]],
  ['vqueuedelete',['vQueueDelete',['../v_queue_delete.html',1,'']]],
  ['vsemaphorecreatebinary',['vSemaphoreCreateBinary',['../group__v_semaphore_create_binary.html',1,'']]],
  ['vsemaphorecreatemutex',['vSemaphoreCreateMutex',['../group__v_semaphore_create_mutex.html',1,'']]],
  ['vsemaphoredelete',['vSemaphoreDelete',['../v_semaphore_delete.html',1,'']]],
  ['vtaskdelay',['vTaskDelay',['../group__v_task_delay.html',1,'']]],
  ['vtaskdelayuntil',['vTaskDelayUntil',['../group__v_task_delay_until.html',1,'']]],
  ['vtaskdelete',['vTaskDelete',['../group__v_task_delete.html',1,'']]],
  ['vtaskendscheduler',['vTaskEndScheduler',['../group__v_task_end_scheduler.html',1,'']]],
  ['vtaskgetruntimestats',['vTaskGetRunTimeStats',['../v_task_get_run_time_stats.html',1,'']]],
  ['vtasklist',['vTaskList',['../v_task_list.html',1,'']]],
  ['vtaskpriorityset',['vTaskPrioritySet',['../group__v_task_priority_set.html',1,'']]],
  ['vtaskresume',['vTaskResume',['../group__v_task_resume.html',1,'']]],
  ['vtaskresumefromisr',['vTaskResumeFromISR',['../group__v_task_resume_from_i_s_r.html',1,'']]],
  ['vtaskstartscheduler',['vTaskStartScheduler',['../group__v_task_start_scheduler.html',1,'']]],
  ['vtasksuspend',['vTaskSuspend',['../group__v_task_suspend.html',1,'']]],
  ['vtasksuspendall',['vTaskSuspendAll',['../group__v_task_suspend_all.html',1,'']]],
  ['vtor',['VTOR',['../struct_s_c_b___type.html#a0faf96f964931cadfb71cfa54e051f6f',1,'SCB_Type']]]
];
